dist: trusty

sudo: enabled

os: linux
  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake
      - valgrind

language: cpp

compiler: gcc

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc;
      sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++;
      export CC=/usr/bin/gcc-7;
      export CXX=/usr/bin/g++-7;
      gcc -v && g++ -v && cmake --version;
    fi 
  - ./setup.sh
  - mkdir build
  - cd build
  - mkdir debug
  - cd debug
  - cmake ../../
  - make -j12
  - ctest  -T memcheck -j12
  - cat ./Testing/Temporary/MemoryChecker.*.log
