dist: trusty

sudo: enabled

os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake

language: 
  - cpp

compiler:
  - gcc

before_install:
  - pip install --user cpp-coveralls

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc;
      sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++;
      export CC=/usr/bin/gcc-7;
      export CXX=/usr/bin/g++-7;
      gcc -v && g++ -v && cmake --version;
    fi 
  - mkdir build
  - cd build
  - mkdir debug
  - cd debug
  - cmake -E env CXXFLAGS="-ftest-coverage -fprofile-arcs --coverage -fno-inline -fno-inline-small-functions -fno-default-inline
" cmake ../../
  - make -j4
  - ctest -j4
  
after_success:
  - coveralls --exclude lib --gcov-options '\-lp'
