os:
  - linux

addons:
  apt:
    packages:
      - gcc-7
      - g++-7

language: cpp

compiler:
  - gcc

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export CC=gcc-7 ;
      export CXX=g++-7 ;
      source /opt/qt510/bin/qt510-env.sh ;
    fi 
  - mkdir build
  - cd build
  - mkdir debug
  - cd debug
  - cmake ../../
  - make -j4
