# Project Configuration

# C++ Project
language: cpp

dist: trusty
sudo: required

# Build Job Matrix

jobs:
    include:

        # Valgrind
        - os: linux
          compiler: gcc
          addons:
              apt:
                  sources: ['ubuntu-toolchain-r-test']
                  packages: ['g++-7', 'cmake', 'ninja-build', 'valgrind', 'libeigen3-dev']
          env:
              - COMPILER="g++-7"
              - CTEST_OPTIONS="-T memcheck"
              - VALGRIND="ON"

        # Coveralls
        - os: linux
          compiler: gcc
          addons:
              apt:
                  sources: ['ubuntu-toolchain-r-test']
                  packages: ['g++-7', 'cmake', 'ninja-build', 'libeigen3-dev']
          before_install:
              - pip install --user cpp-coveralls
          after_success:
              - coveralls --root ../../ --build-root ./ --include include --gcov 'gcov-7' --gcov-options '\-lp'
          env:
              - COMPILER="g++-7"
              - COVERALL="ON"
              - CMAKE_OPTIONS="-DFASTAD_ENABLE_COVERAGE=ON"

        # OSX / Clang

        - os: osx
          osx_image: xcode10

        - os: osx
          osx_image: xcode10.1

        - os: osx
          osx_image: xcode10.2

        - os: osx
          osx_image: xcode11.2

        # Linux/GCC>=5

        - os: linux
          compiler: gcc
          env: COMPILER=g++-7
          addons:
            apt:
              sources: ['ubuntu-toolchain-r-test']
              packages: ['g++-7', 'ninja-build', 'libeigen3-dev']

        - os: linux
          compiler: gcc
          env: COMPILER=g++-8
          addons:
            apt:
              sources: ['ubuntu-toolchain-r-test']
              packages: ['g++-8', 'ninja-build', 'libeigen3-dev']

        - os: linux
          compiler: gcc
          env: COMPILER=g++-9
          addons:
            apt:
              sources: ['ubuntu-toolchain-r-test']
              packages: ['g++-9', 'ninja-build', 'libeigen3-dev']

# Build Script

script:

    # MacOS only: install ninja and cmake
    - if [[ (-x $(which brew)) ]]; then
       brew update;
       brew install cmake ninja eigen;
       brew upgrade cmake;
      fi

    # set CXX to correct compiler
    - if [[ "${COMPILER}" != "" ]]; then
        export CXX=${COMPILER};
      fi 

    # show OS/compiler/cmake version
    - uname -a
    - ${CXX} --version
    - cmake --version

    # setup, clean build, and test
    - ./setup.sh
    - ./clean-build.sh release ${CMAKE_OPTIONS}
    - cd build/release
    - ctest ${CTEST_OPTIONS} -j12

    # if testing valgrind
    - if [[ "${VALGRIND}" == "ON" ]]; then
        cat ./Testing/Temporary/MemoryChecker.*.log;
      fi
