version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:bionic
   
    steps:
      - checkout
      - run:
          name: Install sudo
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Install ubuntu-toolchain-r/test, g++-8, and cmake
          command: |
              sudo apt-get update
              sudo apt-get install -y software-properties-common
              sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
              sudo apt update
              sudo apt install g++-8 -y
              sudo apt install cmake -y
      - run:
          name: Check g++ version
          command: |
              sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 \
                                       --slave /usr/bin/g++ g++ /usr/bin/g++-7 
              sudo update-alternatives --config gcc
              gcc --version
              g++ --version
      - run:
          name: Install Ninja
          command: |
              sudo apt-get update
              sudo apt-get install -y ninja-build
      - run:
          name: Install Git
          command: |
              sudo apt-get update 
              sudo apt-get install -y git
      - run:
          name: Init Submodules
          command: 'git submodule init'
      - run:
          name: Setup
          command: './setup.sh dev'
      - run:
          name: Versions
          command: 'cmake --version; uname -a'
      - run:
          name: Compile
          command: |
              mkdir -p build && cd build
              mkdir -p release && cd release
              rm -rf ./*
              cmake ../../ -GNinja
              cmake --build . -- -j4
      - run:
          name: Execute test suite
          command: 'cd build/release ; ctest -j6'
